sudo: required
language: rust
rust:
  - stable
cache: cargo

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  fast_finish: true
  allow_failures:
    - os: windows
  include:
    - name: windows_x86_64
      os: windows
    - name: linux_x86_64
      os: linux
      addons:
        apt:
          packages:
            - libssl-dev
    - name: macosx_x86_64
      os: osx

script:
  - travis_wait 30 cargo build --verbose
  - travis_wait 30 cargo test --no-fail-fast --verbose --all -- --nocapture
