#[derive(Debug)]
pub enum IndexType {
    Null,
    Char,
    Int8,
    Int16,
    Int32,
    Int64,
    String,
    Bin,
    StringArray,
}

impl From<i32> for IndexType {
    fn from(tag: i32) -> Self {
        match tag {
            0 => IndexType::Null,
            1 => IndexType::Char,
            2 => IndexType::Int8,
            3 => IndexType::Int16,
            4 => IndexType::Int32,
            5 => IndexType::Int64,
            6 => IndexType::String,
            7 => IndexType::Bin,
            8 => IndexType::StringArray,
            _ => IndexType::Null,
        }
    }
}

#[derive(Debug)]
pub enum Tag {
    Image,
    Signatures,
    Immutable,
    Regions,
    i18Ntable,
    Name,
    Version,
    Release,
    Epoch,
    Summary,
    Description,
    BuildTime,
    BuildHost,
    InstallTime,
    Size,
    Distribution,
    Vendor,
    Gif,
    Xpm,
    License,
    Packager,
    Group,
    Changelog,
    Source,
    Patch,
    Url,
    Os,
    Arch,
    PreIn,
    PostIn,
    ReUn,
    PostUn,
    OldFileNames,
    FileSizmes,
    FilesStates,
    FileModes,
    FileUIDs,
    FileGids,
    FilerDevs,
    FileMTimes,
    FileMD5s,
    FileLinktos,
    FileFlags,
    Root,
    FileUserName,
    FileGroupName,
    Exclude,
    Exclusive,
    Icon,
    SourceRpm,
    FileVerifyFlags,
    ArchiveSize,
    ProvideName,
    RequireFlags,
    RequireName,
    RequireVersion,
    NoSource,
    NoPatch,
    Conflictflags,
    Conflictname,
    Conflictversion,
    DefaultPrefix,
    BuildRoot,
    Installprefix,
    Excludearch,
    Excludeos,
    Exclusivearch,
    Exclusiveos,
    Autoreqprov,
    Rpmversion,
    Triggerscripts,
    Triggername,
    Triggerversion,
    Triggerflags,
    Triggerindex,
    Verifyscript,
    Changelogtime,
    ChangelogName,
    Changelogtext,
    Brokenmd5,
    Prereq,
    Preinprog,
    Postinprog,
    Preunprog,
    Postunprog,
    BuildArchs,
    Obsoletename,
    Verifyscriptprog,
    Triggerscriptprog,
    DocDir,
    Cookie,
    FileDevices,
    FileInodes,
    FileLangs,
    Prefixes,
    InstPrefixes,
    Triggerin,
    Triggerun,
    Triggerpostun,
    Autoreq,
    Autoprov,
    Capability,
    Sourcepackage,
    Oldorigfilenames,
    Buildprereq,
    Buildrequires,
    Buildconflicts,
    Buildmacros,
    Provideflags,
    Provideversion,
    Obsoleteflags,
    Obsoleteversion,
    Dirindexes,
    Basenames,
    DirNames,
    Origdirindexes,
    Origbasenames,
    Origdirnames,
    Optflags,
    Disturl,
    Payloadformat,
    Payloadcompressor,
    Payloadflags,
    InstallColor,
    InstallTid,
    Removetid,
    Sha1rhn,
    RHNPlatform,
    Platform,
    PatchesName,
    Catchesflags,
    Catchesversion,
    Cachectime,
    Cachepkgpath,
    Cachepkgsize,
    Cachepkgmtime,
    Filecolors,
    Fileclass,
    Classdict,
    Diledependsx,
    Filedependsn,
    Dependsdict,
    Sourcepkgid,
    FileContexts,
    FsContects,
    ReContexts,
    Policies,
    Other(i32),
}

impl From<i32> for Tag {
    fn from(tag: i32) -> Self {
        match tag {
            61 => Tag::Image,
            62 => Tag::Signatures,
            63 => Tag::Immutable,
            64 => Tag::Regions,
            100 => Tag::i18Ntable,
            1000 => Tag::Name,
            1001 => Tag::Version,
            1002 => Tag::Release,
            1003 => Tag::Epoch,
            1004 => Tag::Summary,
            1005 => Tag::Description,
            1006 => Tag::BuildTime,
            1007 => Tag::BuildHost,
            1008 => Tag::InstallTime,
            1009 => Tag::Size,
            1010 => Tag::Distribution,
            1011 => Tag::Vendor,
            1012 => Tag::Gif,
            1013 => Tag::Xpm,
            1014 => Tag::License,
            1015 => Tag::Packager,
            1016 => Tag::Group,
            1017 => Tag::Changelog,
            1018 => Tag::Source,
            1019 => Tag::Patch,
            1020 => Tag::Url,
            1021 => Tag::Os,
            1022 => Tag::Arch,
            1023 => Tag::PreIn,
            1024 => Tag::PostIn,
            1025 => Tag::ReUn,
            1026 => Tag::PostUn,
            1027 => Tag::OldFileNames,
            1028 => Tag::FileSizmes,
            1029 => Tag::FilesStates,
            1030 => Tag::FileModes,
            1031 => Tag::FileUIDs,
            1032 => Tag::FileGids,
            1033 => Tag::FilerDevs,
            1034 => Tag::FileMTimes,
            1035 => Tag::FileMD5s,
            1036 => Tag::FileLinktos,
            1037 => Tag::FileFlags,
            1038 => Tag::Root,
            1039 => Tag::FileUserName,
            1040 => Tag::FileGroupName,
            1041 => Tag::Exclude,
            1042 => Tag::Exclusive,
            1043 => Tag::Icon,
            1044 => Tag::SourceRpm,
            1045 => Tag::FileVerifyFlags,
            1046 => Tag::ArchiveSize,
            1047 => Tag::ProvideName,
            1048 => Tag::RequireFlags,
            1049 => Tag::RequireName,
            1050 => Tag::RequireVersion,
            1051 => Tag::NoSource,
            1052 => Tag::NoPatch,
            1053 => Tag::Conflictflags,
            1054 => Tag::Conflictname,
            1055 => Tag::Conflictversion,
            1056 => Tag::DefaultPrefix,
            1057 => Tag::BuildRoot,
            1058 => Tag::Installprefix,
            1059 => Tag::Excludearch,
            1060 => Tag::Excludeos,
            1061 => Tag::Exclusivearch,
            1062 => Tag::Exclusiveos,
            1063 => Tag::Autoreqprov,
            1064 => Tag::Rpmversion,
            1065 => Tag::Triggerscripts,
            1066 => Tag::Triggername,
            1067 => Tag::Triggerversion,
            1068 => Tag::Triggerflags,
            1069 => Tag::Triggerindex,
            1070 => Tag::Verifyscript,
            1071 => Tag::Changelogtime,
            1072 => Tag::ChangelogName,
            1073 => Tag::Changelogtext,
            1074 => Tag::Brokenmd5,
            1075 => Tag::Prereq,
            1076 => Tag::Preinprog,
            1077 => Tag::Postinprog,
            1078 => Tag::Preunprog,
            1079 => Tag::Postunprog,
            1080 => Tag::BuildArchs,
            1081 => Tag::Obsoletename,
            1082 => Tag::Verifyscriptprog,
            1083 => Tag::Triggerscriptprog,
            1084 => Tag::DocDir,
            1085 => Tag::Cookie,
            1086 => Tag::FileDevices,
            1087 => Tag::FileInodes,
            1088 => Tag::FileLangs,
            1089 => Tag::Prefixes,
            1090 => Tag::InstPrefixes,
            1091 => Tag::Triggerin,
            1092 => Tag::Triggerun,
            1093 => Tag::Triggerpostun,
            1094 => Tag::Autoreq,
            1095 => Tag::Autoprov,
            1096 => Tag::Capability,
            1097 => Tag::Sourcepackage,
            1098 => Tag::Oldorigfilenames,
            1099 => Tag::Buildprereq,
            1100 => Tag::Buildrequires,
            1101 => Tag::Buildconflicts,
            1102 => Tag::Buildmacros,
            1103 => Tag::Provideflags,
            x => Tag::Other(x),
        }
    }
}
